<HR COLOR=blue>
日志时间：2025-01-16 09:47:16,766 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 套接字操作尝试一个无法连接的主机。
 ---> System.Net.Sockets.SocketException (10065): 套接字操作尝试一个无法连接的主机。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 09:47:20,150 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 套接字操作尝试一个无法连接的主机。
 ---> System.Net.Sockets.SocketException (10065): 套接字操作尝试一个无法连接的主机。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 09:48:42,141 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ReadData S7.Net.PlcException: Unable to read data from the transport connection: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
 ---> System.IO.IOException: Unable to read data from the transport connection: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at S7.Net.StreamExtensions.ReadExactAsync(Stream stream, Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at S7.Net.TPKT.ReadAsync(Stream stream, CancellationToken cancellationToken)
   at S7.Net.COTP.TPDU.ReadAsync(Stream stream, CancellationToken cancellationToken)
   at S7.Net.COTP.TSDU.ReadAsync(Stream stream, CancellationToken cancellationToken)
   at S7.Net.Plc.NoLockRequestTsduAsync(Stream stream, Byte[] requestData, Int32 offset, Int32 length, CancellationToken cancellationToken)
   at S7.Net.Internal.TaskQueue.Enqueue[T](Func`1 action)
   at S7.Net.Plc.ReadMultipleVars(List`1 dataItems)
   --- End of inner exception stack trace ---
   at S7.Net.Plc.ReadMultipleVars(List`1 dataItems)
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 302 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 09:48:45,228 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ReadData S7.Net.PlcException: Unable to write data to the transport connection: 远程主机强迫关闭了一个现有的连接。.
 ---> System.IO.IOException: Unable to write data to the transport connection: 远程主机强迫关闭了一个现有的连接。.
 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsyncForNetworkStream(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.SendAsyncForNetworkStream(ReadOnlyMemory`1 buffer, SocketFlags socketFlags, CancellationToken cancellationToken)
   at System.Net.Sockets.NetworkStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at S7.Net.Plc.NoLockRequestTsduAsync(Stream stream, Byte[] requestData, Int32 offset, Int32 length, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at S7.Net.Plc.NoLockRequestTsduAsync(Stream stream, Byte[] requestData, Int32 offset, Int32 length, CancellationToken cancellationToken)
   at S7.Net.Plc.<>c__DisplayClass79_0.<RequestTsduAsync>b__0()
   at S7.Net.Internal.TaskQueue.Enqueue[T](Func`1 action)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at S7.Net.Plc.ReadMultipleVars(List`1 dataItems)
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 302
   at BMHRI.WCS.Server.Models.SSJDevice.<.ctor>b__63_3() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 260
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.<>c.<.cctor>b__10_0(Object s)
   at System.Threading.Thread.StartCallback()
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at S7.Net.Plc.NoLockRequestTsduAsync(Stream stream, Byte[] requestData, Int32 offset, Int32 length, CancellationToken cancellationToken)
   at S7.Net.Internal.TaskQueue.Enqueue[T](Func`1 action)
   at S7.Net.Plc.ReadMultipleVars(List`1 dataItems)
   --- End of inner exception stack trace ---
   at S7.Net.Plc.ReadMultipleVars(List`1 dataItems)
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 302 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 09:48:48,275 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 套接字操作尝试一个无法连接的主机。
 ---> System.Net.Sockets.SocketException (10065): 套接字操作尝试一个无法连接的主机。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 09:48:51,320 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 套接字操作尝试一个无法连接的主机。
 ---> System.Net.Sockets.SocketException (10065): 套接字操作尝试一个无法连接的主机。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 09:48:54,369 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 套接字操作尝试一个无法连接的主机。
 ---> System.Net.Sockets.SocketException (10065): 套接字操作尝试一个无法连接的主机。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 09:48:57,412 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 套接字操作尝试一个无法连接的主机。
 ---> System.Net.Sockets.SocketException (10065): 套接字操作尝试一个无法连接的主机。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 09:49:00,462 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 套接字操作尝试一个无法连接的主机。
 ---> System.Net.Sockets.SocketException (10065): 套接字操作尝试一个无法连接的主机。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 09:49:03,504 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 套接字操作尝试一个无法连接的主机。
 ---> System.Net.Sockets.SocketException (10065): 套接字操作尝试一个无法连接的主机。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 09:49:06,544 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 套接字操作尝试一个无法连接的主机。
 ---> System.Net.Sockets.SocketException (10065): 套接字操作尝试一个无法连接的主机。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 09:49:09,592 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 套接字操作尝试一个无法连接的主机。
 ---> System.Net.Sockets.SocketException (10065): 套接字操作尝试一个无法连接的主机。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 09:49:12,849 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 套接字操作尝试一个无法连接的主机。
 ---> System.Net.Sockets.SocketException (10065): 套接字操作尝试一个无法连接的主机。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 09:49:15,927 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 套接字操作尝试一个无法连接的主机。
 ---> System.Net.Sockets.SocketException (10065): 套接字操作尝试一个无法连接的主机。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 09:49:19,045 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 套接字操作尝试一个无法连接的主机。
 ---> System.Net.Sockets.SocketException (10065): 套接字操作尝试一个无法连接的主机。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 09:49:22,125 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 套接字操作尝试一个无法连接的主机。
 ---> System.Net.Sockets.SocketException (10065): 套接字操作尝试一个无法连接的主机。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 09:49:25,184 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 套接字操作尝试一个无法连接的主机。
 ---> System.Net.Sockets.SocketException (10065): 套接字操作尝试一个无法连接的主机。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:42:29,066 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:42:53,381 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:43:17,478 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:43:41,557 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:44:05,637 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:44:29,729 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:44:53,816 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:45:17,909 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:45:42,024 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:46:06,109 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:46:30,199 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:46:54,314 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:47:18,408 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:47:42,509 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:48:06,603 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:48:30,708 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:48:54,803 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:49:18,896 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:49:43,024 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:50:07,136 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:50:31,229 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:50:55,336 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:51:19,425 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:51:43,541 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:52:07,642 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 16:52:31,767 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 18:37:54,142 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 18:38:18,393 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 23:23:38,465 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 23:24:02,585 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 23:24:26,678 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 23:27:52,157 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 23:27:52,157 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ02 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.42.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 23:28:20,120 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 23:28:20,138 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ02 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.42.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 23:28:44,211 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 23:28:44,242 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ02 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.42.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 23:29:08,337 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ02 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.42.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 23:29:08,339 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 23:29:32,456 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ02 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.42.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 23:29:32,456 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 23:29:57,543 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ02 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.42.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1><HR COLOR=blue>
日志时间：2025-01-16 23:29:57,543 [.NET Long Running Task] <BR>
日志级别：INFO  <BR>
日 志 类：loginfo [(null)] <BR>
PLC通讯失败，SSJ01 ErrorCode = ConnectionError S7.Net.PlcException: Couldn't establish the connection to 10.192.14.41.
Message: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at S7.Net.Plc.ConnectAsync()
   at S7.Net.Plc.OpenAsync(CancellationToken cancellationToken)
   at S7.Net.Plc.Open()
   --- End of inner exception stack trace ---
   at S7.Net.Plc.Open()
   at BMHRI.WCS.Server.Models.PLCDevice.Connect() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\PLCDevice.cs:line 123
   at BMHRI.WCS.Server.Models.SSJDevice.AutoConnectPLC() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 275
   at BMHRI.WCS.Server.Models.SSJDevice.PLCCommunication() in E:\BMH\2024\得力\1228得力现场\得力立库WCS程序\得力立库WCS程序0111\BMHRI.WCS.Server.20240401\Models\SSJDevice.cs:line 327 <BR>
 <HR Size=1>